### PR TITLE
Fix clone struct

### LINKED ISSUE #426: Nested Nested Nested Nested `StackItem`s could be Out Out Out Out of Memory Again in NeoVM
```
5601c501fe0360589d604a12c0db415824f7cd45
```

### PR DESCRIPTION
**Pull request by shargon**
Close #426

### CODE REVIEW

File: src/neo-vm/Types/Struct.cs [hunk 1]
```diff
@@ -44,6 +47,9 @@ public Struct Clone()
                 Struct b = queue.Dequeue();
                 foreach (StackItem item in b)
                 {
+                    if (count == 0) throw new ArgumentException();
+                    count--;
```
Comment (roman-khimov) [inline src/neo-vm/Types/Struct.cs:51]: It can be an array or map.

Comment (shargon) [reply src/neo-vm/Types/Struct.cs:51]: We can subtract the `SubItemsCount`, but it could have another array inside

Comment (roman-khimov) [reply src/neo-vm/Types/Struct.cs:51]: You've probably seen nspcc-dev/neo-go#2054, I think it's enough to prevent complexity explosion without changing VM behavior (it's possible to return more than `MaxStackSize` items from `Clone` this way, but not a lot more and it'll be checked when item is to be pushed onto the stack).

File: src/neo-vm/Types/Struct.cs [hunk 2]
```diff
@@ -31,9 +32,11 @@ public Struct(ReferenceCounter? referenceCounter, IEnumerable<StackItem>? fields
         /// <summary>
         /// Create a new structure with the same content as this structure. All nested structures will be copied by value.
         /// </summary>
+        /// <param name="limits">Execution engine limits</param>
         /// <returns>The copied structure.</returns>
-        public Struct Clone()
+        public Struct Clone(ExecutionEngineLimits limits)
         {
+            var count = limits.MaxInvocationStackSize - 1;
```
Comment (roman-khimov) [inline src/neo-vm/Types/Struct.cs:39]: BTW, that's for invocation stack, I'm not sure using it for anything item-related is appropriate.

Comment (erikzhang) [reply src/neo-vm/Types/Struct.cs:39]:
```suggestion
            var count = limits.MaxStackSize - 1;
```

**Comment by roman-khimov** [comment]
BTW, don't forget about https://github.com/neo-project/neo-vm/issues/426#issuecomment-878120245. Fixing `Clone` technically doesn't require changing current VM behaviour (as in producing different results for the same script), while fixing `Equals` certainly does.

**Review by erikzhang — DISMISSED** [review]

**Review by erikzhang — APPROVED** [review]

**Comment by ProDog** [comment]
Tested OK, execute `5601c501fe0360589d604a12c0db415824f7cd45` will throw exception `System.ArgumentException: Value does not fall within the expected range`.

**Comment by erikzhang** [comment]
@ProDog I've changed the exception type. Can you test it again?

**Comment by ProDog** [comment]
> @ProDog I've changed the exception type. Can you test it again?

New exception: `System.InvalidOperationException: Operation is not valid due to the current state of the object.`

File: src/neo-vm/Types/Struct.cs [hunk 3]
```diff
@@ -53,8 +57,11 @@ public Struct Clone()
                     }
                     else
                     {
+                        if (item is CompoundType ar)
+                            count -= ar.SubItemsCount;
```
Comment (erikzhang) [inline src/neo-vm/Types/Struct.cs:61]: I think we should remove these 2 lines. Because if a `Struct` contains two identical arrays or maps, the number of their child elements will be counted repeatedly.

**Review by erikzhang — CHANGES_REQUESTED** [review]

File: src/neo-vm/Types/Struct.cs (hunk 3 above)
Comment (superboyiii) [reply src/neo-vm/Types/Struct.cs:61]: @shargon Let's move on.

**Review by erikzhang — APPROVED** [review]

File: src/neo-vm/Types/Struct.cs [hunk 4]
```diff
@@ -45,6 +47,8 @@ public Struct Clone()
                 Struct b = queue.Dequeue();
                 foreach (StackItem item in b)
                 {
+                    count--;
+                    if (count < 0) throw new InvalidOperationException();
```
Comment (cloud8little) [inline src/neo-vm/Types/Struct.cs:51]: any message for the exception should be better?

Comment (superboyiii) [inline src/neo-vm/Types/Struct.cs:51]:
```suggestion
                    if (count < 0) throw new InvalidOperationException("Beyond clone limits!");
```

**Review by cloud8little — APPROVED** [review]

**Review by superboyiii — APPROVED** [review]

**Review by erikzhang — APPROVED** [review]
