### PR TITLE
Fix  PUSHDATA4

### LINKED ISSUE #438: Script checks are incomplete
**Describe the bug**
While we have some instruction parameter checks in https://github.com/neo-project/neo-vm/blob/master/src/neo-vm/Instruction.cs#L197, I think they could be even stricter.
This testnet transaction has the following script `ffd62aab65a143080c0dc0fa23465b236d152d42ca176873c9bf76d6520acbce`:
```
RET
PUSHDATA4 0xFFFFFFFF
```
The parameter for `PUSHDATA4` is decoded as `-1` and thus skipped by the logic above, though it is certainly invalid.

**Expected behavior**
Invalid script is rejected in strict mode.

### PR DESCRIPTION
**Pull request by erikzhang**
Fix #438

### CODE REVIEW

**Comment by erikzhang** [comment]
@fyrchik Please check it.

**Review by shargon — APPROVED** [review]

File: src/neo-vm/Instruction.cs [hunk 1]
```diff
@@ -211,13 +211,14 @@ internal Instruction(byte[] script, int ip) : this((OpCode)script[ip++])
                     break;
                 case 4:
                     operandSize = BitConverter.ToInt32(script, ip);
+                    if (operandSize < 0) throw new BadScriptException();
```
Comment (fyrchik) [inline src/neo-vm/Instruction.cs:214]: Is `CALL_L` ok after this change?

Comment (erikzhang) [reply src/neo-vm/Instruction.cs:214]: `CALL_L` doesn't use `SizePrefix`.
